### ISSUE TITLE
NullPointerException on ScanResultObject.getClassInfo(ScanResultObject.java:47)

### ISSUE THREAD

**Issue by rgoncalves-Bib** [fast-classpath-scanner/fast-classpath-scanner#216]
When using the Scanner from a maven plugin, executed in a project with several module, when the scanner is executed on a module, I get the NPE : io.github.lukehutch.fastclasspathscanner.ScanResultObject.getClassInfo(ScanResultObject.java:47)

Full log : 
```
2018-07-26T09:55:24.722+0200    FastClasspathScanner    Exception thrown
2018-07-26T09:55:24.722+0200    FastClasspathScanner    -- java.util.concurrent.ExecutionException: java.lang.NullPointerException
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.InterruptionChecker.executionException(InterruptionChecker.java:86)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:199)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkQueue(WorkQueue.java:108)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkQueue(WorkQueue.java:122)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner.call(Scanner.java:559)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner.call(Scanner.java:64)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at java.lang.Thread.run(Thread.java:748)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    -- Caused by: java.lang.NullPointerException
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.ScanResultObject.getClassInfo(ScanResultObject.java:47)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.getClassInfo(AnnotationInfo.java:112)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.getParameterValues(AnnotationInfo.java:140)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.toString(AnnotationInfo.java:234)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.toString(AnnotationInfo.java:255)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at java.lang.String.valueOf(String.java:2994)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at java.lang.StringBuilder.append(StringBuilder.java:131)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.Join.join(Join.java:57)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.ClassInfoUnlinked.logTo(ClassInfoUnlinked.java:171)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.ClasspathElement.parseClassfiles(ClasspathElement.java:270)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner$5.processWorkUnit(Scanner.java:563)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner$5.processWorkUnit(Scanner.java:560)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:187)
2018-07-26T09:55:24.722+0200    FastClasspathScanner    --      ... 8 more
2018-07-26T09:55:24.747+0200    FastClasspathScanner    Unexpected exception during scan
2018-07-26T09:55:24.747+0200    FastClasspathScanner    -- java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.util.concurrent.FutureTask.report(FutureTask.java:122)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.util.concurrent.FutureTask.get(FutureTask.java:192)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1008)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1060)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1076)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at com.michelin.mojo.MyMojo.execute(MyMojo.java:61)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.lang.reflect.Method.invoke(Method.java:498)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    -- Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.InterruptionChecker.executionException(InterruptionChecker.java:86)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:199)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkQueue(WorkQueue.java:108)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkQueue(WorkQueue.java:122)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner.call(Scanner.java:559)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner.call(Scanner.java:64)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.lang.Thread.run(Thread.java:748)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    -- Caused by: java.lang.NullPointerException
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.ScanResultObject.getClassInfo(ScanResultObject.java:47)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.getClassInfo(AnnotationInfo.java:112)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.getParameterValues(AnnotationInfo.java:140)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.toString(AnnotationInfo.java:234)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.AnnotationInfo.toString(AnnotationInfo.java:255)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.lang.String.valueOf(String.java:2994)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at java.lang.StringBuilder.append(StringBuilder.java:131)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.Join.join(Join.java:57)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.ClassInfoUnlinked.logTo(ClassInfoUnlinked.java:171)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.ClasspathElement.parseClassfiles(ClasspathElement.java:270)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner$5.processWorkUnit(Scanner.java:563)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.Scanner$5.processWorkUnit(Scanner.java:560)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:187)
2018-07-26T09:55:24.747+0200    FastClasspathScanner    --      ... 8 more

```

**Comment by lukehutch** [comment]
Hi @rgoncalves-Bib, thanks for the report. This should be fixed in 4.0.0-beta-4. Please let me know if it is fixed.

**Comment by rgoncalves-Bib** [comment]
Hi @lukehutch ,
Thank you for the correction. It looks OK. 
However, I may have not understood well your tool, but why : 
```
try {
            scanResult = new FastClasspathScanner()
                    .overrideClasspath(project.getCompileClasspathElements().get(0))
                    .verbose()             // Enable verbose logging
                    .enableAllInfo()   // Scan com.xyz and subpackages
                    .scan();
            ClassInfoList namesOfClassesWithRouteAnnotation =
                    scanResult.getClassesWithAnnotation(Entity.class.getSimpleName());
        } catch (DependencyResolutionRequiredException e) {
            e.printStackTrace();
        }
```

Does not returns classes that are annotated with the given annotation ? It seems to look for annotations classes in my classpath instead of classes annotated with the given annotation

**Comment by lukehutch** [comment]
@rgoncalves-Bib That looks like another bug. I think this is fixed in 4.0.0-beta-5, can you please try with the latest version?

**Comment by rgoncalves-Bib** [comment]
@lukehutch I've tried with the latest version, still not working. 
When debugging the code, I can see all my classes of the  module, but no result for the given annotation.

**Comment by rgoncalves-Bib** [comment]
@lukehutch My mistake ! Working like a charm ! :+1: 

Thank you very much for the quick fixes ! Great tool !

**Comment by giacgbj** [comment]
@rgoncalves-Bib It works only if you use getName() instead of getSimpleName(), right?

@lukehutch It seems that either I don't understand how to use filter or it has a problem with annotations too:
{{{
final ScanResult scanResult = new FastClasspathScanner().enableAllInfo().whitelistPackages("x").scan();
final ClassInfoList entities = scanResult.getAllClasses().filter(c -> c.hasAnnotation(Entity.class.getName()));
}}}

**Comment by lukehutch** [comment]
@rgoncalves-Bib You're right, that was a bug too -- what was happening was that system packages (including `java.*` and `javax.*`) were not being scanned by default, and this included `javax.persistence` etc.

I changed the behavior so that if you're searching *upwards* in the class graph (e.g. looking for annotations, interfaces or superclasses), you get system classes returned (with the exception of `java.lang.Object`, since always returning that as a superclass is probably more annoying than useful) -- or more generally, you get all classes found during the scan, including "external classes" (classes outside of whitelisted packages). However, if you're searching *downwards* in the class graph (e.g. finding classes annotated with a given annotation, or subclasses, or classes that implement an interface), then the results are restricted to classes in whitelisted packages only.

This should be fixed in 4.0.0-beta-6. Please test and let me know.

**Comment by giacgbj** [comment]
@lukehutch Now it works, thanks 👍

**Comment by lukehutch** [comment]
@giacgbj Great, thanks for confirming.

**Comment by rgoncalves-Bib** [comment]
Thanks for your quick fixes !
